### ISSUE TITLE
Filter out IRC text control characters when sending to Slack

### ISSUE THREAD

**Issue by amloessb** [nolanlum/tanya#47]
When text is sent from Tanya to Slack, it can include control characters used to format text in IRC.  These codes do not work in Slack, and appear as strange, printed characters.

For example:
![image](https://user-images.githubusercontent.com/7697831/45473185-36565f00-b6eb-11e8-91e7-8192fb5f2934.png)

![image](https://user-images.githubusercontent.com/7697831/45473199-4b32f280-b6eb-11e8-9829-6d8ffe0c541d.png)

![image](https://user-images.githubusercontent.com/7697831/45473280-86cdbc80-b6eb-11e8-9ae0-e798eec75a19.png)

These control characters should be filtered out of the text that gets sent back to Slack to improve message readability.

**Comment by nolanlum** [comment]
This is a bug with Slack, where it renders non-printable characters as non zero-width. I've reported it to Slack but it's not very high on their priority list, apparently.

Would accepts PRs adding a flag to drop IRC control characters at each individual Tanya instance, but since Slack will passthrough the characters just fine, I wouldn't just want to blanket-strip the formatting codes.

**Comment by kennydo** [comment]
+1

**Comment by derekxwu** [comment]
+1

**Comment by nolanlum** [comment]
Slack now drops control characters on the server side, closing out this issue.
